package certification.oracle;

import java.io.FileNotFoundException;

//public class ExceptionClass {

//	public static void main(String[] args) {
//
//		method1();
//	}
//
//	public static void method1() {
//		method2();
//	}
//
//	public static void method2() {
//		String[] students = { "Shreya", "Joseph" };
//		System.out.println(students[5]);
//	}
//
//}
//====================
//
//class ExceptionClass {
//	void method1() throws Error {
//	}
//
//	void method2() throws Exception {
//	}
//
//	void method3() throws Throwable {
//	}
//
//	void method4() throws RuntimeException {
//	}
//
//	void method5() throws FileNotFoundException {
//	}
//}

//===================
class HandleExceptions {
	void method6() {
		try {
		} catch (Error e) {
		}
	}

	void method7() {
		try {
		} catch (Exception e) {
		}
	}

	void method8() {
		try {
		} catch (Throwable e) {
		}
	}

	void method9() {
		try {
		} catch (RuntimeException e) {
		}
	}

	What happens
	when an
	exception is thrown?

void method10() { try {}
catch (FileNotFoundException e) {}
 



Won’t compile
 
483
 
}
}
